apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-v1
  labels:
    app: demo-app
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
      version: v1
  template:
    metadata:
      labels:
        app: demo-app
        version: v1
    spec:
      containers:
        - name: demo-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tagV1 }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ENDPOINT
              value: {{ .Values.aws.endpoint | quote }}
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.aws.accessKey | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.aws.secretKey | quote }}
            - name: APP_VERSION
              value: "v1"