image:
  repository: docker.io/tmsouza88/demo-calculator
  tagV1: "v1"
  tagV2: "v1"
  pullPolicy: IfNotPresent

service:
  name: demo-app
  type: ClusterIP
  port: 80

aws:
  endpoint: "http://localstack:4566"
  region: "us-east-1"
  accessKey: "test"
  secretKey: "test"

s3:
  bucket: "demo-bucket"

sqs:
  queueName: "demo-queue"